spring:
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        generate_statistics: true
        types:
          print:
            banner: false
  flyway:
    enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    ru.privetdruk: TRACE
    reactor.netty.http.client: TRACE
    org.springframework.cache: TRACE
bot:
  client:
    rest: /client
    username: ${BOT_CLIENT_USERNAME}
    token: ${BOT_CLIENT_TOKEN}
    web-hook-path: ${BOT_CLIENT_WEB_HOOK_PATH}
  user:
    rest: /user
    username: ${BOT_USER_USERNAME}
    token: ${BOT_USER_TOKEN}
    web-hook-path: ${BOT_USER_WEB_HOOK_PATH}

server:
  port: ${SERVER_PORT}

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false
logging:
  level:
    ru.privetdruk: INFO
    reactor.netty.http.client: INFO