spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/restorder
    username: postgres
    password: postgres

bot:
  client:
    username: test
    token: test
    web-hook-path: https://test.test
  user:
    username: test
    token: test
    web-hook-path: https://test.test